version = 0.14

[default.deploy.parameters]
stack_name = "my-app-dev"
s3_prefix = "my-app-dev"
disable_rollback = true
resolve_s3 = true
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
ENV = "development"
confirm_changeset = true

[prod.deploy.parameters]
stack_name = "my-app-production"
s3_prefix = "my-app-production"
disable_rollback = false
resolve_s3 = true
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
ENV = "production"
confirm_changeset = true
