# AWS SAM Tutorial Yaml
# See more https://github.com/serverless-projects/aws-sam-examples/blob/master/samples_1/hello-world/python/template.yaml
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: python3.6
      CodeUri: .